### PR TITLE
Add license injector

### PR DESCRIPTION
**Pull request by dmreagan**
I recently learned of the recommendations from the [IU Open Source Administrators](https://indiana-university.github.io/). They include licensing with BSD-3 and inserting license and copyright info into all source files. This PR adds an npm script which automatically checks for the info and inserts it if it is missing. It can also be configured to search for and remove license info if we need to change things later.

We'll need to check with the Immersive Scholar folks to see if BSD-3 works for them.

### CODE REVIEW

**Comment by guangchen** [comment]
Merged license branch into master

**Comment by dmreagan** [comment]
@guangchen, it looks like you forgot to merge

**Comment by guangchen** [comment]
Need to rollback to previous commit since I found the license branch raises "Access to XMLHttpRequest at has been blocked by CORS policy" error. I suspect this is brought by some newly introduced dependencies in package.json. Dave can you please verify this issue?

**Comment by dmreagan** [comment]
Could it be a problem with the injected license info in one of the files? Like maybe it wasn't commented correctly, or there's a problem having comments at the top of the file? Please check the extra `license_formats` I had to provide in _package.json_ for any mistakes.  The only dependency added to _package.json_ is the utility for injecting the license info, which only runs when you manually execute it.

**Comment by dmreagan** [comment]
Going with #57 for now. May return to this later for individual file injection.

**Pull request closed without merging**
